### PR TITLE
Tidy up some links and add notes

### PR DESCRIPTION
**Pull request by FelisiaM**
Which other branches should this be merged with (if any)?
- 1.2
- master

### CODE REVIEW

**Comment by RichardJJG** [comment]
@thanks, @FelisiaM!

https://github.com/pivotal/csb-brokerpak-azure (referenced in line 100) is now read-only. Should I simply delete that reference?

**Comment by FelisiaM** [comment]
Thanks @RichardJJG 

https://github.com/pivotal/csb-brokerpak-azure has been moved to  https://github.com/cloudfoundy/csb-brokerpak-azure

**Comment by RichardJJG** [comment]
@FelisiaM, another query:

1. Why do we recommend enabling backup and restore capabilities in the MySQL database before attempting encryption?
2. Should this really be a step as part of the procedure? (If we recommend this in all cases, maybe we should just tell the reader to do it and give details or just cross-reference other docs?)

**Comment by FelisiaM** [comment]
1. Why do we recommend enabling backup and restore capabilities in the MySQL database before attempting encryption?
One reason is that it is a requirement for us to document how to backup the supporting DBs. 
Also, enabling encryption will iterate all the databases and try to encrypt sensitive fields. If something goes wrong the customer might be left with a partially encrypted db. In this case, the safest solution is to revert to the last backed up DB.

2. Should this really be a step as part of the procedure? (If we recommend this in all cases, maybe we should just tell the reader to do it and give details or just link to other docs?)
We cannot enforce this since the customer is the one that creates and manages the database - maybe highlighting the recommendation in more places can be good. We cant give links since they could be using any MySQL DB solution that they choose.

**Comment by RichardJJG** [comment]
Thanks, it sounds like your explanation is sufficient, so I'll just add that to the note.

**Pull request merged**
