### PR TITLE
Update docs for Azure MSSQL DB service

### PR DESCRIPTION
**Pull request by FelisiaM**
[#179158078](https://www.pivotaltracker.com/story/show/179158078)

- Which other branches should this be merged with (if any)?
None

### CODE REVIEW

**Comment by RichardJJG** [comment]
Thanks, @FelisiaM!

**Comment by RichardJJG** [comment]
@FelisiaM, re: [the plan storage size table](https://github.com/pivotal-cf/docs-csb-azure/pull/39/files#diff-682a640dbd09f1dd145c38adacf5e20c965880d5947ca88c433e50e84b86d1f5R35),
is the small-v2 plan really the same size as the mini plan? The names suggest that the mini plan is smaller.

**Comment by FelisiaM** [comment]
@RichardJJG 
Yeah, it is. 

It doesn't sound right and maybe the small plan should be a bit larger- but we are not trying to make any behaviour changes so I just documented it as it is today.

**Comment by RichardJJG** [comment]
@FelisiaM, what language formatting should [this code block](https://github.com/pivotal-cf/docs-csb-azure/pull/39/files#diff-682a640dbd09f1dd145c38adacf5e20c965880d5947ca88c433e50e84b86d1f5R279) have?

**Comment by FelisiaM** [comment]
Yes it should be JSON.

**Pull request merged**
