### PR TITLE
Add draft of known issue

### PR DESCRIPTION
**Pull request by blgm**
[#178223703](https://www.pivotaltracker.com/story/show/178223703)

Which other branches should this be merged with (if any)?

### CODE REVIEW

**Comment by jncd** [comment]
Thanks @blgm 
Two questions: (1) I'm going to assume that this known issue is in all 1.1.x versions of CSB-Azure.

**Comment by snneji** [comment]
@bglm, is this issue similar to the first [known issue in 1.1.0](https://docs.pivotal.io/csb-azure/1-1/release-notes.html#1-1-0), which was the [Resolved Issue in 1.1.1](https://docs.pivotal.io/csb-azure/1-1/release-notes.html#1-1-1)?

**Comment by jncd** [comment]
Screen Shot 2021-05-28 at 8 54 47 AM
I wonder if this means they fixed problem with `cf create-service` but not a similar problem with `cf update-service`? 
So that: "Any parameters provided to `cf update-service` are not preserved." I.e. if I run `cf update-service` a second time, my parameters from the first update are not preserved.

**Comment by blgm** [comment]
@jncd:
1) I think so
2) Sounds good

@snneji: that's a good spot. It looks like a `create -> update` issue was fixed, but a `create -> update 1 -> update 2` issue remains (which is this PR). The team has changed completely since then so we don't have any context going back that far.

**Pull request merged**
